name: Deploy to Live Site (Vite → gh-pages)

on:
  push:
    branches: [ main ]

concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
      VITE_API_POST_BASE_URL: ${{ vars.VITE_API_POST_BASE_URL }}

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20.11.1
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Build (mode=custom)
        run: npm run build -- --mode=custom

      - name: SPA 404 fallback
        run: |
          if [ -f dist/index.html ] && [ ! -f dist/404.html ]; then cp dist/index.html dist/404.html; fi

      - name: Add CNAME
        run: echo "inclusiverealitylab.org" > dist/CNAME

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: frontend/dist
